import { Events } from './eventInterface'
    
export const EVENTS: Events[] = [

    {   id: 1,
        activityType: 'Brewery',
        cost: '$',
        location: 'Church Hill',
        activityName: 'Stone Brewing',
        drinks: true,
        food: true,
        outdoor: false,
        free: false,
        family: true,
        art: false,
        history: false,
        music: false,
        educational: false,
    },
    {   id: 2,
        activityType: 'Park',
        cost: 'Free',
        location: 'Randolph',
        activityName: 'Maymont Park',
        drinks: false,
        food: false,
        outdoor: true,
        free: false,
        family: true,
        art: false,
        history: false,
        music: false,
        educational: true,
    },
    {   id: 3,
        activityType: 'Food',
        cost: '$$',
        location: 'Church Hill',
        activityName: 'The Boathouse',
        drinks: true,
        food: true,
        outdoor: true,
        free: false,
        family: true,
        art: false,
        history: false,
        music: false,
        educational: false,
    }
]
